name: Stanley-lua/Stanley
description: Package manager for Lua.
version: 1.1
author: 
  - email: wolf2789@gmail.com
    name: Dawid Bugajski
autoload:
  - type: global
    name: Stanley
    path: src/Stanley.lua
require:
  - name: Stanley-lua/CLI
  - name: Stanley-lua/counter
  - name: Stanley-lua/Debug
  - name: Stanley-lua/File
  - name: Stanley-lua/opairs
  - name: Stanley-lua/oscapture
  - name: Stanley-lua/spairs
  - name: Stanley-lua/switch
  - name: Stanley-lua/YAML
